name: BackupHandler build process

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: BackupHandler
        path: staging

  provide-download-link:
    runs-on: ubuntu-latest
    needs: publish-job
    steps:
    - name: Download BackupHandler artifact
      uses: actions/download-artifact@v4
      with:
        name: BackupHandler
        path: download

    - name: Upload BackupHandler
      uses: actions/upload-artifact@v4
      with:
        name: BackupHandler
        path: $GITHUB_WORKSPACE/staging

    - name: Provide download link
      run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/_apis/artifact?name=BackupHandler&path=staging"
